/************animate Header Background */
const
  list = [
    ['HTML5', 9],
    ['CSS', 8],
    ['Javascript', 11],
    ['Typescript', 7],
    ['jQuery', 1],
    ['Bootstrap', 1],
    ['Canvas', 1],
    ['RESTful', 4],
    ['ajax', 4],
    ['angular', 4],
    ['Vue', 4],
    ['React', 22],
    ['Chart.js', 1],
    ['DataTables.js', 3],
    ['Adobe XD', 3],
    ['Photoshop', 1],
    ['illustrator', 2],
    ['inDesign', 12],
    ['Premiere', 3],
    ['After Effect', 6],
    ['GIT', 6],
    ['gitHub', 3],
    ['vTigerCRM', 3],
    ['webpack', 12],
    ['Stylus', 12],
    ['SASS', 12],
    ['SCSS', 10],
    ['RWD', 10],
    ['ES6', 9],
    ['Node.js', 9],
    ['Hexo', 9],
    ['PHP', 10],
    ['MySQL', 9],
    ['Laravel', 6],
    ['MongoDB', 15],
    ['Redux', 10],
    ['CCNA', 3],
    ['Loki', 15],
    ['Jiang', 12],
    ['Wordpress', 3],
    ['Joomla', 6],
    ['fetch', 3],
    ['CROS', 9],
    ['SEO', 6],
    ['JSON/parse', 9],
    ['animation', 6],
    ['transform', 8],
    ['MediaQuery', 3],
    ['SVG', 6],
    ['setTimeOut', 3],
    ['setInterval', 6],
    ['addEventLisition', 9],
    ['Type', 3],
    ['formData', 9],
    ['GET', 6],
    ['POST', 3]
  ],
  lokiKeyword = WordCloud(document.getElementById('lokiBanner'), {
    list: list,
    minFontSize: 10,
    backgroundColor: '#666',
    color: function (word, weight) {
      return weight > 10 ? '#E9106166' :
        ['#0006', '#1116', '#2226', '#3336', '#4446', '#5556'][Math.floor(Math.random() * 6)];
    },
    rotateRatio: 0.5,
    rotationSteps: 2,
    gridSize: 20,
    weightFactor: 5,
    drawOutOfBound: false,
    shrinkToFit: true,
    wait: 50
  });